# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: gato-os
description: Gato OS - A very WIP distro that will feel like magic.
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 43

modules:
    - type: files
      files:
          - source: theming
            destination: /usr/share/gato/theming
          - source: wallpapers
            destination: /usr/share/backgrounds/gato
          - source: gato-daemon.service
            destination: /usr/lib/systemd/user/gato-daemon.service
          - source: gato-cosmic-setup.sh
            destination: /usr/bin/gato-cosmic-setup

    - type: rpm-ostree
      repos:
          - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-43/atim-starship-fedora-43.repo
      install:
          - git
          - golang
          - podman
          - distrobox
          - htop
          - ripgrep
          - fd-find
          - bat
          - starship
          - fzf
          - zoxide
          - ImageMagick
          - curl
          - wget
          - jq
      remove:
          - firefox
          - firefox-langpacks

    - type: fonts
      fonts:
          google-fonts:
              - Google Sans Flex
              - Google Sans Code

    - type: containerfile
      snippets:
          # Install RPM Fusion repos and full ffmpeg
          - RUN rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
          - RUN rpm-ostree override remove ffmpeg-free libavcodec-free libavdevice-free libavfilter-free libavformat-free libavutil-free libpostproc-free libswresample-free libswscale-free --install=ffmpeg
          # Build gato from source
          - COPY gato-daemon /tmp/gato-build
          - RUN cd /tmp/gato-build && go build -o /usr/bin/gato ./cmd/gato && go build -o /usr/bin/gato-daemon ./cmd/gato-daemon && rm -rf /tmp/gato-build
          # Make COSMIC setup script executable and enable daemon
          - RUN chmod +x /usr/bin/gato-cosmic-setup
          - RUN systemctl --global enable gato-daemon.service

    - type: containerfile
      snippets:
          # Install Helium browser (AppImage)
          - RUN curl -L -o /usr/bin/helium https://github.com/imputnet/helium-linux/releases/download/0.7.7.1/helium-0.7.7.1-x86_64.AppImage && chmod +x /usr/bin/helium
          - RUN /usr/bin/mkdir -p /usr/share/applications && echo -e '[Desktop Entry]\nName=Helium Browser\nExec=/usr/bin/helium %U\nIcon=web-browser\nType=Application\nCategories=Network;WebBrowser;\nMimeType=text/html;text/xml;application/xhtml+xml;\nComment=Privacy-focused Chromium-based browser' > /usr/share/applications/helium.desktop

    - type: soar
      additional-repos: true
      auto-upgrade: true
      upgrade-interval: "3h"

    - type: default-flatpaks
      configurations:
          - notify: true
            scope: system
            repo:
                title: Flathub
            install:
                - dev.zed.Zed
                - org.videolan.VLC
                - org.gnome.Loupe
                - com.github.tchx84.Flatseal
                - org.mozilla.firefox
                - it.mijorus.gearlever

    - type: containerfile
      snippets:
          # COSMIC conf (Theme + Wallpaper)
          - |
              RUN mkdir -p /usr/share/cosmic/themes && \
                  cp /usr/share/gato/theming/gato-dark.ron /usr/share/cosmic/themes/ && \
                  mkdir -p /usr/share/cosmic/com.system76.CosmicTheme/v1/ && \
                  echo '(active: "gato-dark", mode: Dark)' > /usr/share/cosmic/com.system76.CosmicTheme/v1/theme && \
                  mkdir -p /usr/share/cosmic/com.system76.CosmicBackground/v1/ && \
                  cat > /usr/share/cosmic/com.system76.CosmicBackground/v1/all <<'EOF'
                  (
                      output: "all",
                      source: Path("/usr/share/backgrounds/gato/gato-wp2.png"),
                      filter_by_theme: true,
                      rotation_frequency: 300,
                      filter_method: Lanczos,
                      scaling_mode: Zoom,
                      sampling_method: Alphanumeric,
                  )
              EOF
